- name: Clone Git repository, commit changes, and push to new branch
  hosts: myhost
  become: true

  vars:
    git_repo: "https://github.com/myusername/myrepo.git"
    git_branch: "main"
    git_local_dir: "/tmp/myrepo"
    file_path: "/tmp/myrepo/myfile.txt"
    commit_message: "Update myfile.txt"
    new_branch_name: "mybranch"

  tasks:
    - name: Clone Git repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ git_local_dir }}"
        version: "{{ git_branch }}"
        clone: yes

    - name: Create or modify myfile.txt
      copy:
        dest: "{{ file_path }}"
        content: "Hello World!"

    - name: Add myfile.txt to the Git index
      git:
