---
- name: Create Jira Story
  hosts: localhost
  gather_facts: false

  vars:
    jira_base_url: "https://your-jira-instance.com"
    jira_username: "your-jira-username"
    jira_password: "your-jira-password"
    jira_project_key: "PROJECT"

  tasks:
    - name: Create Jira Story
      jira_issue:
        server_url: "{{ jira_base_url }}"
        username: "{{ jira_username }}"
        password: "{{ jira_password }}"
        project: "{{ jira_project_key }}"
        summary: "Your story summary"
        description: "Your story description"
        issue_type: "Story"
      register: issue_result

    - name: Display Jira Story Key
      debug:
        msg: "Jira Story created with key {{ issue_result.key }}"
